### ISSUE TITLE
Reactor fuel dump and Reactor shutdown on server reset

### ISSUE THREAD

**Issue by IWenton** [BiggerSeries/BiggerReactors#78] opened 2023-02-25 23:28 UTC
Currently using a 13x7x9 (LxWxH exterior) reactor on a ATM 8 server hosted by g-portal, it is placed inside of a Maximum compact machine and chunk loaded via ftbchunks. I am also using computer craft to control the reactor (this does not seem to be a factor). After every server reset, any fuel in my reactor gets voided and the reactor is turned off. I'm currently mitigating the fuel issue by overproducing uranium with other mods. I have no idea how to keep my reactor from turning off.

**Comment by RogueLogix** [comment] 2023-03-19 03:35
duplicate of #71

**Closed by RogueLogix** 2023-03-19 03:36 UTC
Labels: bug, Duplicate, 1.19

**Comment by IWenton** [comment] 2023-03-23 00:36
Fuel dump only happens on server reset and not world join
