### ISSUE TITLE
Crash when placing down turbine.

### ISSUE THREAD

**Issue by ChonkyMonkey** [BiggerSeries/BiggerReactors#57] opened 2022-07-22 19:24 UTC
My game crashed as I was completing the turbine multi-block by placing down the last turbine shaft.
As the build transformed into the multiblock my game crashed. I am playing forge ATM 7 in 1.18.2 with 4 additional performance mods: 
rubidium, radium, radon and oculus. Ah and by the way the generator multi-block seems to work just fine.
Here is the crash code:

[crash-2022-07-22_19.55.44-client.txt](https://github.com/BiggerSeries/BiggerReactors/files/9170165/crash-2022-07-22_19.55.44-client.txt)

Later I did some testing and it seems like rubidium and oculus do not like turbines. Without these mods the turbine assebles just fine.
So: This mod is not compatible with rubidium but I would love the devs if they fixed it since rubidium is performance wise pretty essential.

**Comment by RogueLogix** [comment] 2022-07-22 19:49
duplicate of BiggerSeries/Quartz#6

**Closed by RogueLogix** 2022-07-22 19:49 UTC
Labels: bug, duplicate
