### ISSUE TITLE
Reactor voiding fuel when joining world [0.6.0-beta.6]

### ISSUE THREAD

**Issue by dredgemage** [BiggerSeries/BiggerReactors#71] opened 2023-01-25 04:18 UTC
I'm running an All The Mods 8 server and a couple of my players have reported that when logging out and logging back in the reactor's fuel will be gone. I had them test without any automatic fuel inset or waste extract and it still occurred. Screenshot below. I am unable to replicate the issue in a single player world. 

![2023-01-24_21 42 01](https://user-images.githubusercontent.com/6761184/214476934-47599311-cd77-4491-a64a-887d3e80caf2.png)

**Comment by dredgemage** [comment] 2023-01-27 22:23
Update: Reassembling the reactor 1 block to the east (back and left in the picture) so that it is no longer adjacent to the chunk boundary resolves this issue.

**Comment by OgleTr122b** [comment] 2023-02-09 09:51
I've had the same issue on ATM 8. After messing around with the mod, it seems to happen on worlds with specific seeds and the reactor is unloaded and reloaded. It can be through leaving and returning to the dimension or the area with the reactor in it. It doesn't seem to caused by the surrounding blocks or entities as I made a new world with the same seed and traveled 10,000 blocks away from where I initially encountered the problem and it persisted. In case it's helpful, I built a reactors with a 1 - 4 fuel rods, both 1 - 2 access ports, and a single power tap. I even moved the controller to another side of the reactor to see if that would help to no avail.  The seed: 4016083079836001191

**Comment by RogueLogix** [comment] 2023-02-09 23:58
I'm unable to reproduce this as described in singleplayer or on a server

**Comment by Talkarcabbage** [comment] 2023-02-18 02:35
So far I don't think it is related to being on a chunk border.

**Comment by RogueLogix** [comment] 2023-03-19 18:56
Finally was able to reproduce a potentially related bug, its a race condition, and wont reproduce on my desktop but will my server

**Comment by RogueLogix** [comment] 2023-03-25 16:46
Bug that was reproduced could easily cause this, so removing that label, but as I can't easily reproduce it, I will leave this issue open for a while after in case its not fixed.

**Comment by Lord-Volkner** [comment] 2023-03-31 07:52
Now running:

biggerreactors-1.19.2-0.6.0-beta.6.1

I'm not sure how to tell, but best I can figure this is the most recent.

Unfortunately the problem still exists for me.

**Comment by estafeit** [comment] 2023-04-17 16:12
Same problem here, with ATM 8 and beta 6.1, on a freshly built reactor. Reactor is totally inside, and not touching, chunk boundaires. If I can be of any help.

**Comment by RogueLogix** [comment] 2023-04-17 16:17
If you can make it happen reliably, that's what I really need. It's basically impossible for.me.to try and fix this by poking in the dark.

If reloading your world is all it takes and it does it every time, then I'll need your world so I can attach a debugger to it.

**Comment by RogueLogix** [comment] 2023-04-17 16:17
If you can make it happen reliably, that's what I really need. It's basically impossible for me to try and fix this by poking in the dark.

If reloading your world is all it takes and it does it every time, then I'll need your world so I can attach a debugger to it.

**Comment by estafeit** [comment] 2023-04-17 16:27
I guess it is, I mean, I only restarted the word three times for now.
Do you need the whole instance or only save ?
Also, can I upload that kind of file here ? (the savegame only is 500Mb, )

**Comment by RogueLogix** [comment] 2023-04-17 16:29
Just the savegame is fine, if you want you can send it or a link to it, to me on discord (server link on CurseForge) or here, whichever you prefer.

**Comment by estafeit** [comment] 2023-04-17 16:43
Here it is, don't mind the name ^^'

https://1drv.ms/u/s!Aq-PKGxMbagF7Xgr2E0Rtzlyepeq?e=IN51Ar

I don't know if you need details but it's a GDLauncher instance of latest ATM 8 (1.0.15, updated yesterday)

* I added some minor mods, but I think you'll be find without them (just in case : More Concrete, Redstone Pen, Scannable and a fix and update for Advanced peripherals)
* Also I have minecraft lighting bug, making some chunks dark without reasons. So either you clear cache before loading or get mobs spawning on the roofs even in daylight...

**Comment by Lord-Volkner** [comment] 2023-04-17 17:27
> If you can make it happen reliably, that's what I really need. It's basically impossible for me to try and fix this by poking in the dark.
> 
> If reloading your world is all it takes and it does it every time, then I'll need your world so I can attach a debugger to it.

Let me know if you need mine also. My save game folder is 4.31 GB. Not sure what is "just the savegame" other than the whole save folder, but I'm sure I could delete a bunch of the region data and such to make it a more manageable size.

**Comment by RogueLogix** [comment] 2023-04-23 18:54
reproduced in @estafeit's world

**Comment by RogueLogix** [comment] 2023-04-23 19:42
reproduced in dev environment.
reproduction requires a multiblock (this effects turbines too) to be reloaded before first completion. this gets the NBT into a weird state where it skips writing to all blocks.

immediate solution is to completely rebuild the effected multiblock without reloading it until the next phos version that will have it fixed

**Comment by Lord-Volkner** [comment] 2023-04-23 19:56
> immediate solution is to completely rebuild the effected multiblock without reloading it ...

What does that mean?

**Comment by RogueLogix** [comment] 2023-04-23 19:59
remove every block of the reactor and rebuild it without exiting the area.

if singleplayer, just grab this phos version once its done building
https://github.com/BiggerSeries/Phosphophyllite/releases/tag/0.6.0-beta.7.1

**Comment by estafeit** [comment] 2023-04-24 04:14
Following your procedure definitely solved it for me. The end of power shortages ! Thank you.

**Comment by RogueLogix** [comment] 2023-04-24 15:25
As this issue appears to be actually be fixed now, I'm going to close this issue. If it continues, comment and I'll reopen it.

**Closed by RogueLogix** 2023-04-24 15:25 UTC
Labels: bug, 1.19, Priority: Critical
