### ISSUE TITLE
[1.19.2] ATM8 multiblock crash

### ISSUE THREAD

**Issue by Mitchell5200** [BiggerSeries/BiggerReactors#63] opened 2022-09-20 05:36 UTC
again, that fun one, confirmed that a player was re-assembling a reactor when it crashed
 
phosphophyllite-1.19.2-0.6.0-beta.5.jar
biggerreactors-1.19.2-0.6.0-beta.5.1.jar
forge 43.1.25
 
[crash-2022-09-20_05.27.13-server.txt](https://github.com/BiggerSeries/BiggerReactors/files/9604346/crash-2022-09-20_05.27.13-server.txt)

**Comment by RogueLogix** [comment] 2022-09-20 05:50
duplicate of Biggerseries/Phosphophyllite#23

**Closed by RogueLogix** 2022-09-20 05:50 UTC
Labels: bug, duplicate
