### ISSUE TITLE
ATM7 0.4.16 - Entire server crashed

### ISSUE THREAD

**Issue by Waffleflappers** [BiggerSeries/BiggerReactors#53] opened 2022-06-26 08:33 UTC
My entire personal server crashed the moment I pressed the "On" switch on a reactor. The reactor was built inside of a compact machine, the largest size. Two crash logs were generated.
[latest.log](https://github.com/BiggerSeries/BiggerReactors/files/8986257/latest.log)
[crash-2022-06-26_10.00.14-server.txt](https://github.com/BiggerSeries/BiggerReactors/files/8986258/crash-2022-06-26_10.00.14-server.txt)
[crash-2022-06-26_09.59.12-server.txt](https://github.com/BiggerSeries/BiggerReactors/files/8986259/crash-2022-06-26_09.59.12-server.txt)

**Comment by Waffleflappers** [comment] 2022-06-26 08:43
![2022-06-26_03 36 36](https://user-images.githubusercontent.com/13159995/175806530-9bc63b74-589f-40f8-82fd-db1f8aaba837.png)
This is what happened after my server rebooted. I had originally placed the reactor terminal on the bottom spot, but then I learned that it needed to be in the glass part, so when I turned the reactor on, the bottom terminal spot was a reactor casing block, and the top terminal was where it is in the screenshot

**Comment by RogueLogix** [comment] 2022-06-26 17:29
Duplicate of BiggerSeries/Phosphophyllite#23, please add a comment on that issue.

**Closed by RogueLogix** 2022-06-26 17:29 UTC
Labels: bug, duplicate, Weird, Higgs Bugson
