### ISSUE TITLE
Reactor Shutting off and instantly voiding fuel when out of chunk

### ISSUE THREAD

**Issue by MoonsMcSparkle** [BiggerSeries/BiggerReactors#74] opened 2023-02-18 06:19 UTC
I am using the bigger reactors mod 1.19.2-0.6.0-beta.6 and whenever I leave the chunk, which is chunk loaded, my reactor will shut off and all of the fuel I had put in there will just be voided.

**Comment by RogueLogix** [comment] 2023-03-19 03:35
duplicate of #71

**Closed by RogueLogix** 2023-03-19 03:35 UTC
Labels: bug, Duplicate, 1.19
